# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-09-05 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speech',
            name='number',
        ),
    ]
